[package]
name = "screenshots_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
screenshots = "0.5.3"
cmake = "0.1"
chrono = "0.4.23"
opencv = "0.78.0"
